#! /bin/sh
###########################
## https://github.com/crustware/OldbandT

### Environment ###
export PATH="${PATH}:$HOME/.config/bspwm"

### Coloring ###
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources
COLOR=$(shuf -n1 -e ~/.colors/*)
SHORTCOLOR=$(echo $COLOR | sed "s@.*/@@")
xrdb -merge $COLOR
paintee
# Only use the function above if the cache of paintee couldn't be found
if [ -e ~/.cache/paintee ]; then
	. ~/.cache/paintee
	else
	getcolors
fi

### Bspwm Monitors/workspaces ###
bspc monitor DisplayPort-0 -d 5 6
bspc monitor HDMI-A-0 -d 1 2 3 4

### Bspwm Configuration ###
bspc config focused_border_color    "$BACKGROUND"
bspc config normal_border_color     "$BACKGROUND"
bspc config active_border_color     "$BACKGROUND"
bspc config presel_feedback_color   "$RED"
bspc config focus_follows_pointer    false
bspc config borderless_monocle       false
bspc config gapless_monocle          false
bspc config paddingless_monocle      true
bspc config single_monocle           true
bspc config remove_disabled_monitors true
bspc config split ratio              0.50
bspc config border_width             2
bspc config window_gap               8

## Window rules assignments ###
# remove all rules first
bspc rule -r *:*

bspc rule -a Pavucontrol state=floating rectangle 700x300+24+240 sticky=false
bspc rule -a Galculator state=floating rectange 500x50+24+240 sticky=false

# > Video
bspc rule -a mpv desktop='^6' follow=on focus=on

### Autostart ###
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --pos 0x0 --rotate right --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 1080x0 --rotate normal &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
dunst -config ~/.config/dunst/dunstrc &
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done
polybar -c ~/.config/bspwm/polybar right &
polybar -c ~/.config/bspwm/polybar left &
jellyfin-mpv-shim











