#!/bin/sh
# DESC: Elvi to search animetosho
# elvis: animetosho	-- Search animetosho (animetosho)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
search animetosho.org for content
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://animetosho.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://animetosho.org/search?q=${escaped_args}"
fi
