#!/bin/sh
# DESC: Elvi to search archive.org
# elvis: archive	-- Search archive.org (www.archive.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search archive (www.archive.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.archive.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://archive.org/search.php?query=${escaped_args}"
fi
